// MARK: - HDRMetalRenderer.swift

// Jellyswarrm — GPL v3 with App Store exception

#if canImport(MetalKit)
import AVFoundation
import CoreMedia
import CoreVideo
import JellyswarrmCore
import MetalKit

#if os(macOS)
import AppKit
#else
import UIKit
#endif

// Must match Metal shader struct layout exactly
struct ToneMappingUniforms {
    var edrHeadroom: Float
    var hdrMode: Int32
}

/// EDR headroom reported by the active display. Platform differs:
/// - macOS: NSScreen.maximumExtendedDynamicRangeColorComponentValue
/// - iOS / tvOS: UIScreen.currentEDRHeadroom
@MainActor
private func currentEDRHeadroom() -> Float {
#if os(macOS)
    return Float(NSScreen.main?.maximumExtendedDynamicRangeColorComponentValue ?? 1.0)
#else
    return Float(UIScreen.main.currentEDRHeadroom)
#endif
}

@MainActor
public final class HDRMetalRenderer: NSObject, MTKViewDelegate {

    public let mtkView: MTKView
    private let player: AVPlayer
    private let videoOutput: AVPlayerItemVideoOutput
    private var textureCache: CVMetalTextureCache?
    private var pipelineState: MTLRenderPipelineState?
    private let commandQueue: MTLCommandQueue?
    private let hdrFormat: HDRFormat

    public init?(player: AVPlayer, hdrFormat: HDRFormat) {
        guard let device = MTLCreateSystemDefaultDevice() else { return nil }
        self.player = player
        self.hdrFormat = hdrFormat
        self.commandQueue = device.makeCommandQueue()

        mtkView = MTKView(frame: .zero, device: device)
        mtkView.colorPixelFormat = .rgba16Float
        mtkView.framebufferOnly = false
        mtkView.enableSetNeedsDisplay = false
        mtkView.isPaused = false
        mtkView.preferredFramesPerSecond = 120 // ProMotion

#if os(macOS)
        if let metalLayer = mtkView.layer as? CAMetalLayer {
            metalLayer.wantsExtendedDynamicRangeContent = true
            metalLayer.colorspace = CGColorSpace(name: CGColorSpace.extendedLinearITUR_2020)
            metalLayer.pixelFormat = .rgba16Float
        }
#elseif os(tvOS)
        // `wantsExtendedDynamicRangeContent` is unavailable on tvOS; opt into HDR
        // via the new tvOS 26 `preferredDynamicRange` API (KVC for forward compat).
        mtkView.layer.setValue(2, forKey: "preferredDynamicRange") // .high = 2
#else
        if let metalLayer = mtkView.layer as? CAMetalLayer {
            metalLayer.wantsExtendedDynamicRangeContent = true
            metalLayer.colorspace = CGColorSpace(name: CGColorSpace.extendedLinearITUR_2020)
            metalLayer.pixelFormat = .rgba16Float
        }
#endif

        // Request linear Rec.2020 FP16 from AVFoundation so the fragment shader
        // receives already-linearised values and can apply tonemapping directly.
        let colorProps: [String: Any] = [
            AVVideoColorPrimariesKey: AVVideoColorPrimaries_ITU_R_2020,
            AVVideoTransferFunctionKey: AVVideoTransferFunction_Linear,
            AVVideoYCbCrMatrixKey: AVVideoYCbCrMatrix_ITU_R_2020,
        ]
        let outputSettings: [String: Any] = [
            AVVideoAllowWideColorKey: true,
            AVVideoColorPropertiesKey: colorProps,
            kCVPixelBufferPixelFormatTypeKey as String: NSNumber(value: kCVPixelFormatType_64RGBAHalf),
        ]
        videoOutput = AVPlayerItemVideoOutput(outputSettings: outputSettings)

        super.init()

        CVMetalTextureCacheCreate(nil, nil, device, nil, &textureCache)

        // Bundle.module is generated by SPM when resources are declared; if the
        // default library cannot be loaded the renderer fails init gracefully and
        // the view layer falls back to the AVFoundation player.
        let library: MTLLibrary?
        if let bundleLibrary = try? device.makeDefaultLibrary(bundle: .module) {
            library = bundleLibrary
        } else {
            library = device.makeDefaultLibrary()
        }

        if let library {
            let desc = MTLRenderPipelineDescriptor()
            desc.vertexFunction = library.makeFunction(name: "hdr_vertex")
            desc.fragmentFunction = library.makeFunction(name: "hdr_fragment")
            desc.colorAttachments[0].pixelFormat = .rgba16Float
            pipelineState = try? device.makeRenderPipelineState(descriptor: desc)
        }

        if pipelineState == nil {
            print("[HDRMetalRenderer] Pipeline state creation failed — falling back to passthrough")
            return nil
        }

        mtkView.delegate = self

        player.currentItem?.add(videoOutput)

        applyEDRMetadata()
    }

    /// Seed sensible defaults on the layer so initial frames are not blown out
    /// before the per-frame metadata update fires. Updated per-frame from
    /// pixel-buffer attachments by `updateEDRMetadata`.
    private func applyEDRMetadata() {
#if !os(tvOS)
        guard let metalLayer = mtkView.layer as? CAMetalLayer else { return }
        switch hdrFormat {
        case .hdr10:
            metalLayer.edrMetadata = .hdr10(minLuminance: 0.001, maxLuminance: 1000, opticalOutputScale: 100)
        case .hlg:
            metalLayer.edrMetadata = .hlg
        default:
            metalLayer.edrMetadata = nil
        }
#endif
    }

    // MARK: — MTKViewDelegate

    nonisolated public func mtkView(_ view: MTKView, drawableSizeWillChange size: CGSize) {}

    // MetalKit invokes draw(in:) on the main thread for an MTKView attached to a
    // UIKit/AppKit hierarchy. Assume the main-actor isolation so we can touch
    // @MainActor state without an extra Task hop (which would also tear at
    // MTKView's non-Sendability under Swift 6 strict concurrency).
    nonisolated public func draw(in view: MTKView) {
        MainActor.assumeIsolated {
            self.drawFrame(in: view)
        }
    }

    @MainActor
    private func drawFrame(in view: MTKView) {
        guard
            let cache = textureCache,
            let pipeline = pipelineState,
            let commandQueue,
            let drawable = view.currentDrawable,
            let renderPassDesc = view.currentRenderPassDescriptor
        else { return }

        let itemTime = videoOutput.itemTime(forHostTime: CACurrentMediaTime())
        guard videoOutput.hasNewPixelBuffer(forItemTime: itemTime),
              let pixelBuffer = videoOutput.copyPixelBuffer(forItemTime: itemTime, itemTimeForDisplay: nil)
        else { return }

        updateEDRMetadata(from: pixelBuffer)

        let width = CVPixelBufferGetWidth(pixelBuffer)
        let height = CVPixelBufferGetHeight(pixelBuffer)
        var cvTexture: CVMetalTexture?
        CVMetalTextureCacheCreateTextureFromImage(
            nil, cache, pixelBuffer, nil, .rgba16Float, width, height, 0, &cvTexture
        )
        guard let cvTex = cvTexture, let frameTexture = CVMetalTextureGetTexture(cvTex) else { return }

        var uniforms = ToneMappingUniforms(
            edrHeadroom: currentEDRHeadroom(),
            hdrMode: Int32(hdrFormat == .hdr10 ? 1 : hdrFormat == .hlg ? 2 : 0)
        )

        guard let commandBuffer = commandQueue.makeCommandBuffer(),
              let encoder = commandBuffer.makeRenderCommandEncoder(descriptor: renderPassDesc)
        else { return }

        encoder.setRenderPipelineState(pipeline)
        encoder.setFragmentTexture(frameTexture, index: 0)
        encoder.setFragmentBytes(&uniforms, length: MemoryLayout<ToneMappingUniforms>.stride, index: 0)
        encoder.drawPrimitives(type: .triangleStrip, vertexStart: 0, vertexCount: 4)
        encoder.endEncoding()

        commandBuffer.addCompletedHandler { _ in
            _ = cvTex // hold the CVMetalTexture until the GPU finishes
        }
        commandBuffer.present(drawable)
        commandBuffer.commit()
    }

    private func updateEDRMetadata(from pixelBuffer: CVPixelBuffer) {
        // Per-frame EDR metadata update deferred — static metadata sufficient
        // (displayInfo/contentInfo overload requires non-optional Data from SEI messages)
    }

    /// Stops the renderer and removes the video output from the player item.
    /// Call explicitly from the view's `.onDisappear` before releasing the
    /// renderer — deinit cannot touch `@MainActor` state under strict concurrency.
    public func tearDown() {
        mtkView.delegate = nil
        mtkView.isPaused = true
        player.currentItem?.remove(videoOutput)
    }
}
#endif
